### ISSUE TITLE
Style Guide

### ISSUE THREAD

**Issue by PossibilityResult** [duality-labs/duality#155]

**Comment by itamarreif** [comment]
[relevant notes from colin & itamar's audit during the retreat](https://www.notion.so/colin-itamar-audit-notes-5f4dd670c5804bb49ae7b931ca7881d6#73142b35bc3142b1be5a7b048b49d6c3)

**Comment by teddyknox** [comment]
We can keep a running doc but will wait until it's a burning need to dedicate resources here.

**Comment by teddyknox** [comment]
https://www.notion.so/dualityxyz/The-Way-of-Duality-28ed9f59d8ab46019ce37390b4cb5d3a
