### ISSUE TITLE
Design Incentivization Mechanics

### ISSUE THREAD

**Issue by eljhfx** [duality-labs/duality#188]
Adds liquidity but doesn't change shares.

Should do this to for tokenized positions.

**Comment by eljhfx** [comment]
We should decide whether we want to do this or not.

Pros
easy to implement
potential tool for liquidity incentives

Cons
extra work
not completely necessary once we have tokenizer

**Comment by teddyknox** [comment]
Feels like it would be better to implement separately rather than interfere with true trading statistics

**Comment by eljhfx** [comment]
Closing this issue to combine with #189
