### ISSUE TITLE
Unify validation and execution

### ISSUE THREAD

**Issue by teddyknox** [duality-labs/duality#194]
Right now we do validation in batch but we do execution order by order. Would be better if we did validation order by order as well. We can unify validation and execution into a single function, where a section at the top handles validation.

**Comment by jcompagni10** [comment]
I think this is the right approach. 
@itamarreif and I talked about this a bit. The biggest question for me is how much overhead there is for each message server request. If overhead is negligible each msgserver request should just specify a single action and SDK/frontend should handle batching. If overhead is high we should stick with batching but probably handle verification and execution in a more symmetrical way

**Comment by teddyknox** [comment]
I don't think there is any real advantage to batching from a computational perspective.
