### ISSUE TITLE
Implement Simulate Swap Query

### ISSUE THREAD

**Issue by eljhfx** [duality-labs/duality#208]
It is extremely useful to have a query where users can input the trade details and get out important data from it. We might want to refactor the swap function to not duplicate code for this.

- [ ] Define scope and Spec Simulate Swap
- [ ] Modularize the swap function or create a new one
- [ ] New unit tests for the query only

**Comment by teddyknox** [comment]
May be related to #191

**Comment by teddyknox** [comment]
Putting a pause on this until @NicholasDotSol is done with his investigation of whether the Cosmos SDK-level simulate is adequate for our needs.

**Comment by teddyknox** [comment]
@NicholasDotSol saying that it should be possible to achieve without a specific query endpoint, closing.
